project: 
  type: website
  
bibliography: references.bib
csl: apa7.csl
format: 
  revealjs:
    theme: custom.scss
    slide-number: true
    slide-level: 2
    embed-resources: true
    sc-sb-title: true
    logo: images/LMLLOGO.png
    footer: <https://littlemonkeylab.com>
    header: Example YAML-based Header
    header-logo: images/GoldLogo.png
    controls: true
    controls-layout: edges
    controls-tutorial: true
    preview-links: true

filters:
  - reveal-header